FROM rust:latest
COPY scripts/* /bin/
RUN  install-package-dependencies.sh \
  && install-clippy.sh \
  && install-rustfmt.sh \
  && install-musl-cross-compilation.sh \
  && install-cargo-build-deps.sh \
  && install-cargo-cache.sh \
  && rm /bin/install-*.sh \
  && cargo cache --remove-dir all \
  && echo 'echo-buildenv.sh' >> ~/.bashrc \
  && echo-buildenv.sh
