FROM rustlang/rust:nightly
COPY scripts/* /bin/
RUN  install-package-dependencies.sh \
  && install-clippy.sh \
  && install-rustfmt.sh \
  && install-musl-cross-compilation.sh \
  && rm /bin/install-*.sh \
  && echo 'echo-buildenv.sh' >> ~/.bashrc \
  && echo-buildenv.sh
